server:
  port: 8085


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: blog-service
          uri: lb://auth-service
          predicates:
            - Path=/blog/**
          filters:
            - StripPrefix=1