server:
  port: 8085


springdoc:
  swagger-ui:
    configUrl: /swagger-config.json
    path: /v1/swagger-ui.html
  api-docs:
    path: /v1/api-docs

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/blog/**
          filters:
            - StripPrefix=1